version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
       - mongo-data:/data/db
       - mongo-config:/data/configdb
    env_file:
      - ./backend/.env
    networks:
      - fullstack-chat
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5
## Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - fullstack-chat
    depends_on:
      - mongo
## frontend----------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - fullstack-chat
    depends_on:
      - backend
networks:
  fullstack-chat:
    driver: bridge
volumes:
  mongo-data:
  mongo-config:
